#!/usr/bin/env python3
"""ts_domain.py - put an Odoo website on its real domain. Runs ON eot-odoo-prod as root
(use `ts domain ...` from the VPS). One command replaces the ~25 hand-typed calls of the
2026-09-29 talentsearch.ir cutover.

  ts_domain.py check   DOMAIN [--website ID]
        read-only: authoritative DNS, cert, nginx, live probes (curl --resolve to this server,
        so a stale resolver cache can never fool it). Also the post-cutover verify.
  ts_domain.py cutover DOMAIN --website ID --from-domain https://old.host [--wait SECS] [--dry-run]
        DNS gate (must be DNS-only/grey, authoritative NS) -> certbot (idempotent) -> nginx conf
        (backup, nginx -t, auto-restore) -> website.domain (+ Kavenegar webhook base) with
        preconditions -> odoo restart (website domain is ormcache'd) -> full verify.
Canonical host = apex; www 301s to it. Aborts loud; every mutating step is idempotent."""
import argparse, os, re, subprocess, sys, time

IP = '95.38.235.225'          # this server's public IP
DB = 'eot_main'
ODOO_SVC = 'odoo20'
UPSTREAM = '127.0.0.1:8069'
SITES = '/etc/nginx/sites-available'
ENABLED = '/etc/nginx/sites-enabled'
FAILS = []


def say(tag, name, detail=''):
    print(f'{tag:5} {name}: {detail}'.rstrip(), flush=True)
    if tag == 'FAIL':
        FAILS.append(name)


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def sh(cmd):
    return run(['bash', '-c', cmd])


def q(s):
    return "'" + str(s).replace("'", "''") + "'"


def psql(sql):
    r = run(['runuser', '-u', 'odoo', '--', 'env', 'HOME=/opt/odoo', 'psql', '-d', DB,
             '-v', 'ON_ERROR_STOP=1', '-tAF', '|', '-c', sql])
    if r.returncode:
        raise RuntimeError(f'psql failed: {r.stderr.strip()[:300]}')
    return [l for l in r.stdout.splitlines() if l.strip() and not l.startswith(('BEGIN', 'COMMIT', 'UPDATE'))]


def fetch(url, host_ips=(), headers=(), head_only=False):
    """curl with --resolve to this server. Returns dict(code, location, hdr, body, rc)."""
    cmd = ['curl', '-sS', '-m', '30', '-D', '-', '-o', '/tmp/ts_domain_body']
    for h, port in host_ips:
        cmd += ['--resolve', f'{h}:{port}:{IP}']
    for h in headers:
        cmd += ['-H', h]
    cmd.append(url)
    r = run(cmd)
    hdr = r.stdout.split('\r\n\r\n')[-2] if '\r\n\r\n' in r.stdout else r.stdout
    m = re.search(r'HTTP/[\d.]+ (\d+)', hdr)
    loc = re.search(r'(?im)^location:\s*(\S+)', hdr)
    try:
        body = open('/tmp/ts_domain_body', encoding='utf-8', errors='ignore').read()
    except OSError:
        body = ''
    return dict(code=int(m.group(1)) if m else 0, location=loc.group(1) if loc else '',
                hdr=hdr, body=body, rc=r.returncode, err=r.stderr.strip()[:200])


def dns_state(domain):
    """{name: set(ips)} from each authoritative NS; returns (ok, problems)."""
    ns = sh(f'dig +short NS {domain}').stdout.split()
    problems = []
    if not ns:
        return False, ['no NS records found']
    for name in (domain, 'www.' + domain):
        seen = set()
        for n in ns:
            seen |= set(sh(f'dig +short @{n} {name} A').stdout.split())
        if seen != {IP}:
            problems.append(f'{name} -> {sorted(seen) or "nothing"} (need only {IP}; if these are Cloudflare IPs '
                            f'set the record to DNS only / grey cloud)')
    return not problems, problems


def cert_info(domain):
    p = f'/etc/letsencrypt/live/{domain}/fullchain.pem'
    if not os.path.exists(p):
        return None
    san = sh(f'openssl x509 -in {p} -noout -ext subjectAltName').stdout
    end = sh(f'openssl x509 -in {p} -noout -enddate').stdout.strip().split('=')[-1]
    days = int(sh(f'echo $(( ($(date -d "{end}" +%s) - $(date +%s)) / 86400 ))').stdout.strip() or 0)
    return dict(covers=all(f'DNS:{n}' in san for n in (domain, 'www.' + domain)), days=days)


def conf_path(domain):
    r = sh(f'grep -lE "server_name[^;]*\\b{re.escape(domain)}\\b" {SITES}/* 2>/dev/null | grep -v "\\.bak" | head -1')
    return r.stdout.strip() or f'{SITES}/{domain.replace(".", "-")}.conf'


def render_conf(domain, tls):
    slug = domain.replace('.', '_')
    acme = 'location ^~ /.well-known/acme-challenge/ { root /var/www/letsencrypt; try_files $uri =404; }'
    proxy = f'''proxy_pass http://up_{slug};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 720s;'''
    head = f'# {domain} - generated by ts_domain.py (DNS-only record, TLS terminated here)\nupstream up_{slug} {{ server {UPSTREAM}; }}\n'
    if not tls:
        return head + f'''server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};
    {acme}
    location / {{ {proxy.replace(chr(10) + "        ", " ")} }}
}}
'''
    crt = f'ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;\n    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;'
    return head + f'''server {{
    listen 80;
    listen [::]:80;
    server_name {domain} www.{domain};
    {acme}
    location / {{ return 301 https://{domain}$request_uri; }}
}}
server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.{domain};
    {crt}
    return 301 https://{domain}$request_uri;
}}
server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};
    {crt}
    client_max_body_size 50M;
    location / {{
        {proxy}
    }}
}}
'''


def install_conf(domain, tls):
    path = conf_path(domain)
    bak = path + '.bak'
    had = os.path.exists(path)
    if had:
        sh(f'cp -p {path} {bak}')
    open(path, 'w').write(render_conf(domain, tls))
    link = f'{ENABLED}/{os.path.basename(path)}'
    if not os.path.exists(link):
        os.symlink(path, link)
    t = run(['nginx', '-t'])
    if t.returncode:
        if had:
            sh(f'cp -p {bak} {path}')
        else:
            os.remove(path); os.remove(link)
        raise RuntimeError('nginx -t failed, config restored: ' + t.stderr.strip()[-300:])
    run(['systemctl', 'reload', 'nginx'])
    say('OK', 'nginx', f'{os.path.basename(path)} {"TLS" if tls else "http-only"} reloaded')


def wait_odoo(secs=120):
    t0 = time.time()
    while time.time() - t0 < secs:
        r = fetch(f'http://{UPSTREAM}/web/login', headers=['Host: x'])
        if r['code'] in (200, 303):
            return True
        time.sleep(3)
    return False


def website_row(wid):
    rows = psql(f'select id,name,domain from website where id={int(wid)}')
    if not rows:
        raise RuntimeError(f'website {wid} not found')
    i, name, dom = rows[0].split('|')
    return name, dom


def webhook_bits():
    cols = psql("select 1 from information_schema.columns where table_name='res_company' and column_name='kv_webhook_secret'")
    if not cols:
        return None
    rows = psql('select kv_webhook_secret, kv_webhook_base from res_company where kv_webhook_secret is not null order by id limit 1')
    return tuple(rows[0].split('|')) if rows else None


def verify(domain, wid):
    R = [(domain, 443), (f'www.{domain}', 443), (domain, 80), (f'www.{domain}', 80)]
    ok, probs = dns_state(domain)
    say('OK' if ok else 'FAIL', 'dns', 'apex+www -> ' + IP + ' on authoritative NS' if ok else '; '.join(probs))
    ci = cert_info(domain)
    if not ci:
        say('FAIL', 'cert', 'none')
    else:
        say('OK' if ci['covers'] and ci['days'] > 14 else 'FAIL', 'cert', f'covers apex+www={ci["covers"]}, {ci["days"]} days left')
    r = fetch(f'http://{domain}/x', R)
    say('OK' if r['code'] == 301 and r['location'] == f'https://{domain}/x' else 'FAIL', 'http->https', f'{r["code"]} {r["location"]}')
    r = fetch(f'https://www.{domain}/x', R)
    say('OK' if r['code'] == 301 and r['location'] == f'https://{domain}/x' else 'FAIL', 'www->apex', f'{r["code"]} {r["location"]} {r["err"]}')
    r = fetch(f'https://{domain}/', R)
    body = r['body']
    title = (re.search(r'<title>([^<]*)', body) or [0, '-'])[1].strip()[:70]
    canon = (re.search(r'rel="canonical" href="([^"]+)"', body) or [0, ''])[1]
    noindex = bool(re.search(r'(?i)noindex', r['hdr'])) or bool(re.search(r'(?i)<meta[^>]+robots[^>]+noindex', body))
    good = r['code'] == 200 and r['rc'] == 0 and canon.startswith(f'https://{domain}') and not noindex
    say('OK' if good else 'FAIL', 'https-home', f'{r["code"]} tls_rc={r["rc"]} canonical={canon or "-"} noindex={noindex} title={title}')
    r = fetch(f'https://{domain}/web/login', R)
    say('OK' if r['code'] == 200 else 'FAIL', 'login', str(r['code']))
    if wid:
        # other sites must be untouched: every other website still answers with its own canonical
        for i, name, dom in [x.split('|') for x in psql(f'select id,name,domain from website where id<>{int(wid)} order by id')]:
            host = re.sub(r'^https?://', '', dom)
            r = fetch(f'http://{UPSTREAM}/', headers=[f'Host: {host}', 'X-Forwarded-Proto: https'])
            c = (re.search(r'rel="canonical" href="([^"]+)"', r['body']) or [0, ''])[1]
            say('OK' if r['code'] in (200, 301, 303) and (host in c or r['code'] != 200) else 'FAIL', f'other-site {i}', f'{dom} -> {r["code"]} {c}')
    wb = webhook_bits()
    if wb:
        secret = wb[0]
        a = fetch(f'https://{domain}/kavenegar/{secret}/status?messageId=0&status=0', R)['code']
        b = fetch(f'https://{domain}/kavenegar/wrong/status', R)['code']
        say('OK' if (a, b) == (200, 404) else 'FAIL', 'webhook', f'good-secret={a} bad-secret={b}')
        print(f'INFO  webhook URLs (paste into Kavenegar): https://{domain}/kavenegar/{secret}/status  |  .../inbound', flush=True)


def cutover(a):
    domain = a.domain
    name, cur = website_row(a.website)
    target = f'https://{domain}'
    say('INFO', 'website', f'{a.website} "{name}" domain={cur}')
    if cur != target and cur != a.from_domain:
        raise RuntimeError(f'precondition: website domain is {cur}, expected {a.from_domain} or {target}')
    if a.wait:
        t0 = time.time()
        while True:
            ok, probs = dns_state(domain)
            if ok or time.time() - t0 > a.wait:
                break
            print(f'wait  dns: {"; ".join(probs)[:200]}', flush=True)
            time.sleep(20)
    ok, probs = dns_state(domain)
    if not ok:
        raise RuntimeError('DNS gate: ' + '; '.join(probs))
    say('OK', 'dns', 'gate passed')
    if a.dry_run:
        say('INFO', 'dry-run', f'would: cert={"present" if cert_info(domain) else "issue"}, nginx conf {conf_path(domain)}, '
            f'website {a.website} domain {cur} -> {target}, restart {ODOO_SVC}')
        return
    ci = cert_info(domain)
    if not (ci and ci['covers']):
        install_conf(domain, tls=False)
        r = run(['certbot', 'certonly', '--webroot', '-w', '/var/www/letsencrypt', '-d', domain, '-d', f'www.{domain}',
                 '--non-interactive', '--agree-tos', '--register-unsafely-without-email', '--keep-until-expiring'])
        if r.returncode:
            raise RuntimeError('certbot: ' + (r.stdout + r.stderr).strip()[-400:])
        say('OK', 'certbot', 'issued')
    else:
        say('OK', 'certbot', f'existing cert ok ({ci["days"]} days)')
    install_conf(domain, tls=True)
    changed = False
    if cur != target:
        psql(f'begin; update website set domain={q(target)} where id={int(a.website)} and domain={q(cur)}; commit;')
        changed = True
        say('OK', 'website.domain', f'{cur} -> {target}')
    wb = webhook_bits()
    if wb and wb[1] == a.from_domain:
        psql(f'update res_company set kv_webhook_base={q(target)} where kv_webhook_base={q(a.from_domain)}')
        say('OK', 'kv_webhook_base', f'{a.from_domain} -> {target}')
    if changed:
        run(['systemctl', 'restart', ODOO_SVC])
        say('OK' if wait_odoo() else 'FAIL', 'odoo restart', ODOO_SVC)
    verify(domain, a.website)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('mode', choices=['check', 'cutover'])
    p.add_argument('domain')
    p.add_argument('--website', type=int)
    p.add_argument('--from-domain')
    p.add_argument('--wait', type=int, default=0)
    p.add_argument('--dry-run', action='store_true')
    a = p.parse_args()
    if a.domain.startswith(('eot.ir', 'www.eot.ir')) or a.website == 1:
        sys.exit('refusing: eot.ir / website 1 is never touched by this tool')
    try:
        if a.mode == 'check':
            verify(a.domain, a.website)
        else:
            if not a.website or not a.from_domain:
                sys.exit('cutover needs --website ID and --from-domain URL')
            cutover(a)
    except RuntimeError as e:
        say('FAIL', 'abort', str(e))
    print('VERDICT: ' + ('ALL OK' if not FAILS else 'FAILED -> ' + ', '.join(FAILS)))
    sys.exit(1 if FAILS else 0)


if __name__ == '__main__':
    main()
