{
    'name': 'Talent Search - Panel v2',
    'summary': 'Panel v2: roles and permissions, clients, invitations, reports, audit, lifecycle (website 2 only). S0 = tooling and two fixes.',
    'version': '20.0.2.0.0',
    'category': 'Services/Talent Search',
    'author': 'EOT',
    'license': 'LGPL-3',
    'depends': ['ts_talent', 'ts_sms'],
    'data': [
        'security/ir.access.csv',
        'views/report_share.xml',
        'views/web_shell.xml',
        'views/web_dashboard.xml',
        'views/web_settings.xml',
        'views/web_clients.xml',
        'views/web_client.xml',
        'views/web_members.xml',
        'views/web_member.xml',
        'views/web_help_roles.xml',
        'views/web_reauth.xml',
        'views/layout_inherit.xml',
    ],
    'assets': {
        'ts_website.assets_ts': ['ts_panel/static/src/scss/panel.scss'],
        'ts_website.assets_ts_js': ['ts_panel/static/src/js/panel.js'],
    },
    'installable': True,
}
