{
    'name': 'Talent Search - Panel v2',
    'summary': 'Panel v2: roles and permissions, clients, invitations, reports, audit, lifecycle (website 2 only). S0 = tooling and two fixes.',
    'version': '20.0.12.0.0',
    'category': 'Services/Talent Search',
    'author': 'EOT',
    'license': 'LGPL-3',
    'depends': ['ts_talent', 'ts_sms'],
    'data': [
        'security/ir.access.csv',
        'data/cron.xml',
        'data/wallet.xml',
        'views/report_share.xml',
        'views/web_shell.xml',
        'views/web_dashboard.xml',
        'views/web_settings.xml',
        'views/web_clients.xml',
        'views/web_client.xml',
        'views/web_client_form.xml',
        'views/web_client_merge.xml',
        'views/web_invites.xml',
        'views/web_campaigns.xml',
        'views/web_import.xml',
        'views/web_exports.xml',
        'views/web_credits.xml',
        'views/web_reports.xml',
        'views/web_audit.xml',
        'views/backend_support.xml',
        'views/backend_wallet.xml',
        'views/web_groups.xml',
        'views/web_members.xml',
        'views/web_member.xml',
        'views/web_help_roles.xml',
        'views/web_reauth.xml',
        'views/backend_notify.xml',
        'views/web_notifications.xml',
        'views/web_my.xml',
        'views/web_consent.xml',
        'views/layout_inherit.xml',
    ],
    'assets': {
        'ts_website.assets_ts': ['ts_panel/static/src/scss/panel.scss'],
        'ts_website.assets_ts_js': ['ts_panel/static/src/js/panel.js'],
    },
    'installable': True,
}
